# Generated by Django 4.1.7 on 2023-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='autor'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='foto',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='biblioteca'),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='libro'),
        ),
        migrations.AddField(
            model_name='libro',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
